import type {
  Semester,
  Subject,
  AttendanceStats,
  Slot,
  SubSlot,
  ClassSchedule,
  ClassOccurrence,
  Exam,
  Task,
  Event,
  ClasseyFile,
  ResourceLink,
  Note,
} from "@/types/database";

/**
 * Mock semester data for development
 * This will be replaced with Appwrite queries
 */
export const mockSemesters: Semester[] = [
  {
    $id: "sem-1",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "semesters",
    $databaseId: "classey",
    $permissions: [],
    name: "Semester 6",
    start_date: "2024-01-15",
    end_date: "2024-05-15",
    color: "#8B5CF6",
    icon: null,
    target_spi: 8.5,
    spi: null,
    credits_earned: null,
    credits_total: 24,
    is_quick_input: false,
    status: "ongoing",
    is_archived: false,
    sort_order: 0,
    deleted_at: null,
  },
  {
    $id: "sem-2",
    $createdAt: "2023-07-01T00:00:00.000Z",
    $updatedAt: "2023-12-20T00:00:00.000Z",
    $collectionId: "semesters",
    $databaseId: "classey",
    $permissions: [],
    name: "Semester 5",
    start_date: "2023-07-01",
    end_date: "2023-12-01",
    color: "#10B981",
    icon: null,
    target_spi: 8.0,
    spi: 8.7,
    credits_earned: 22,
    credits_total: 22,
    is_quick_input: false,
    status: "completed",
    is_archived: false,
    sort_order: 1,
    deleted_at: null,
  },
  {
    $id: "sem-3",
    $createdAt: "2023-01-01T00:00:00.000Z",
    $updatedAt: "2023-05-30T00:00:00.000Z",
    $collectionId: "semesters",
    $databaseId: "classey",
    $permissions: [],
    name: "Semester 4",
    start_date: "2023-01-01",
    end_date: "2023-05-30",
    color: "#F59E0B",
    icon: null,
    target_spi: 8.0,
    spi: 8.2,
    credits_earned: 20,
    credits_total: 20,
    is_quick_input: false,
    status: "completed",
    is_archived: false,
    sort_order: 2,
    deleted_at: null,
  },
];

/**
 * Mock subject data for development
 */
export const mockSubjects: Subject[] = [
  {
    $id: "sub-1",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "subjects",
    $databaseId: "classey",
    $permissions: [],
    semester_id: "sem-1",
    name: "Data Structures & Algorithms",
    short_name: "DSA",
    code: "CS301",
    start_date: null,
    end_date: null,
    color: "#8B5CF6",
    icon: null,
    attendance_requirement_percent: 75,
    credits: 4,
    grade: null,
    grade_points: null,
    grade_scale_id: null,
    type: "theory",
    slot_ids: ["1"],
    teacher_name: "Dr. Smith",
    teacher_email: null,
    teacher_phone: null,
    telegram_notify_classes: false,
    sort_order: 0,
    deleted_at: null,
  },
  {
    $id: "sub-2",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "subjects",
    $databaseId: "classey",
    $permissions: [],
    semester_id: "sem-1",
    name: "Machine Learning",
    short_name: "ML",
    code: "CS302",
    start_date: null,
    end_date: null,
    color: "#EC4899",
    icon: null,
    attendance_requirement_percent: 75,
    credits: 4,
    grade: null,
    grade_points: null,
    grade_scale_id: null,
    type: "theory",
    slot_ids: ["2"],
    teacher_name: "Dr. Johnson",
    teacher_email: null,
    teacher_phone: null,
    telegram_notify_classes: false,
    sort_order: 1,
    deleted_at: null,
  },
  {
    $id: "sub-3",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "subjects",
    $databaseId: "classey",
    $permissions: [],
    semester_id: "sem-1",
    name: "Computer Networks",
    short_name: "CN",
    code: "CS303",
    start_date: null,
    end_date: null,
    color: "#06B6D4",
    icon: null,
    attendance_requirement_percent: 75,
    credits: 3,
    grade: null,
    grade_points: null,
    grade_scale_id: null,
    type: "theory",
    slot_ids: ["3"],
    teacher_name: "Prof. Williams",
    teacher_email: null,
    teacher_phone: null,
    telegram_notify_classes: false,
    sort_order: 2,
    deleted_at: null,
  },
  {
    $id: "sub-4",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "subjects",
    $databaseId: "classey",
    $permissions: [],
    semester_id: "sem-1",
    name: "Operating Systems Lab",
    short_name: "OS Lab",
    code: "CS304",
    start_date: null,
    end_date: null,
    color: "#F59E0B",
    icon: null,
    attendance_requirement_percent: 80,
    credits: 2,
    grade: null,
    grade_points: null,
    grade_scale_id: null,
    type: "lab",
    slot_ids: ["L1"],
    teacher_name: "Dr. Brown",
    teacher_email: null,
    teacher_phone: null,
    telegram_notify_classes: false,
    sort_order: 3,
    deleted_at: null,
  },
];

/**
 * Mock attendance stats for subjects
 */
export const mockAttendanceStats: Record<string, AttendanceStats> = {
  "sub-1": {
    total: 24,
    present: 20,
    absent: 3,
    cancelled: 1,
    percentage: 87,
    classesNeeded: 0,
    canBunk: 5,
  },
  "sub-2": {
    total: 22,
    present: 17,
    absent: 4,
    cancelled: 1,
    percentage: 81,
    classesNeeded: 0,
    canBunk: 2,
  },
  "sub-3": {
    total: 18,
    present: 13,
    absent: 5,
    cancelled: 0,
    percentage: 72,
    classesNeeded: 2,
    canBunk: 0,
  },
  "sub-4": {
    total: 8,
    present: 7,
    absent: 1,
    cancelled: 0,
    percentage: 88,
    classesNeeded: 0,
    canBunk: 1,
  },
};

/**
 * Generate a unique ID for mock data
 */
export function generateMockId(): string {
  return `mock-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Create mock Appwrite document fields
 */
export function createMockDocument(collectionId: string): Omit<Semester | Subject, keyof (Semester | Subject)> & {
  $id: string;
  $createdAt: string;
  $updatedAt: string;
  $collectionId: string;
  $databaseId: string;
  $permissions: string[];
} {
  const now = new Date().toISOString();
  return {
    $id: generateMockId(),
    $createdAt: now,
    $updatedAt: now,
    $collectionId: collectionId,
    $databaseId: "classey",
    $permissions: [],
  };
}

/**
 * Day of week mapping (1=Monday to 6=Saturday)
 */
export const DAY_NAMES: Record<number, string> = {
  1: "Monday",
  2: "Tuesday",
  3: "Wednesday",
  4: "Thursday",
  5: "Friday",
  6: "Saturday",
};

export const DAY_SHORT_NAMES: Record<number, string> = {
  1: "Mon",
  2: "Tue",
  3: "Wed",
  4: "Thu",
  5: "Fri",
  6: "Sat",
};

/**
 * Default slots based on typical college timetable
 * 15 regular slots + 4 lab slots + Wednesday extra slots
 */
const createSubSlots = (slots: Omit<SubSlot, "id">[], prefix: string): SubSlot[] =>
  slots.map((s, i) => ({ ...s, id: `${prefix}${String.fromCharCode(65 + i)}` }));

export const mockSlots: Slot[] = [
  // Regular Slots 1-15 (each has 3 sub-slots on different days)
  {
    $id: "slot-1",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "1",
    name: "Slot 1",
    type: "regular",
    sub_slots: JSON.stringify(createSubSlots([
      { day_of_week: 1, start_time: "08:30", end_time: "09:25" },
      { day_of_week: 2, start_time: "09:30", end_time: "10:25" },
      { day_of_week: 4, start_time: "10:35", end_time: "11:30" },
    ], "1")),
    is_default: true,
    sort_order: 1,
    deleted_at: null,
  },
  {
    $id: "slot-2",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "2",
    name: "Slot 2",
    type: "regular",
    sub_slots: JSON.stringify(createSubSlots([
      { day_of_week: 1, start_time: "09:30", end_time: "10:25" },
      { day_of_week: 2, start_time: "10:35", end_time: "11:30" },
      { day_of_week: 5, start_time: "08:30", end_time: "09:25" },
    ], "2")),
    is_default: true,
    sort_order: 2,
    deleted_at: null,
  },
  {
    $id: "slot-3",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "3",
    name: "Slot 3",
    type: "regular",
    sub_slots: JSON.stringify(createSubSlots([
      { day_of_week: 1, start_time: "10:35", end_time: "11:30" },
      { day_of_week: 4, start_time: "08:30", end_time: "09:25" },
      { day_of_week: 5, start_time: "09:30", end_time: "10:25" },
    ], "3")),
    is_default: true,
    sort_order: 3,
    deleted_at: null,
  },
  {
    $id: "slot-4",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "4",
    name: "Slot 4",
    type: "regular",
    sub_slots: JSON.stringify(createSubSlots([
      { day_of_week: 1, start_time: "11:35", end_time: "12:30" },
      { day_of_week: 2, start_time: "08:30", end_time: "09:25" },
      { day_of_week: 4, start_time: "09:30", end_time: "10:25" },
    ], "4")),
    is_default: true,
    sort_order: 4,
    deleted_at: null,
  },
  {
    $id: "slot-5",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "5",
    name: "Slot 5",
    type: "regular",
    sub_slots: JSON.stringify(createSubSlots([
      { day_of_week: 2, start_time: "11:35", end_time: "12:30" },
      { day_of_week: 4, start_time: "11:35", end_time: "12:30" },
      { day_of_week: 5, start_time: "10:35", end_time: "11:30" },
    ], "5")),
    is_default: true,
    sort_order: 5,
    deleted_at: null,
  },
  // Lab Slots (3-hour continuous blocks)
  {
    $id: "slot-L1",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "L1",
    name: "Lab L1",
    type: "lab",
    sub_slots: JSON.stringify([
      { id: "L1A", day_of_week: 1, start_time: "14:00", end_time: "17:00" },
    ] as SubSlot[]),
    is_default: true,
    sort_order: 16,
    deleted_at: null,
  },
  {
    $id: "slot-L2",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "L2",
    name: "Lab L2",
    type: "lab",
    sub_slots: JSON.stringify([
      { id: "L2A", day_of_week: 2, start_time: "14:00", end_time: "17:00" },
    ] as SubSlot[]),
    is_default: true,
    sort_order: 17,
    deleted_at: null,
  },
  {
    $id: "slot-L3",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "L3",
    name: "Lab L3",
    type: "lab",
    sub_slots: JSON.stringify([
      { id: "L3A", day_of_week: 4, start_time: "14:00", end_time: "17:00" },
    ] as SubSlot[]),
    is_default: true,
    sort_order: 18,
    deleted_at: null,
  },
  {
    $id: "slot-L4",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "L4",
    name: "Lab L4",
    type: "lab",
    sub_slots: JSON.stringify([
      { id: "L4A", day_of_week: 5, start_time: "14:00", end_time: "17:00" },
    ] as SubSlot[]),
    is_default: true,
    sort_order: 19,
    deleted_at: null,
  },
  // Wednesday Extra Slots
  {
    $id: "slot-X1",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "X1",
    name: "Extra X1",
    type: "extra",
    sub_slots: JSON.stringify([
      { id: "X1", day_of_week: 3, start_time: "08:30", end_time: "09:25" },
    ] as SubSlot[]),
    is_default: true,
    sort_order: 20,
    deleted_at: null,
  },
  {
    $id: "slot-X2",
    $createdAt: "2024-01-01T00:00:00.000Z",
    $updatedAt: "2024-01-01T00:00:00.000Z",
    $collectionId: "slots",
    $databaseId: "classey",
    $permissions: [],
    slot_id: "X2",
    name: "Extra X2",
    type: "extra",
    sub_slots: JSON.stringify([
      { id: "X2", day_of_week: 3, start_time: "09:30", end_time: "10:25" },
    ] as SubSlot[]),
    is_default: true,
    sort_order: 21,
    deleted_at: null,
  },
];

/**
 * Mock class schedules (generated from subject slot assignments)
 */
export const mockClassSchedules: ClassSchedule[] = [
  // DSA (Slot 1): Mon 8:30, Tue 9:30, Thu 10:35
  {
    $id: "sched-1",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    slot_id: "slot-1",
    sub_slot_id: "1A",
    day_of_week: 1,
    start_time: "08:30",
    end_time: "09:25",
    room: "LH-101",
    building: "Academic Block A",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
  {
    $id: "sched-2",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    slot_id: "slot-1",
    sub_slot_id: "1B",
    day_of_week: 2,
    start_time: "09:30",
    end_time: "10:25",
    room: "LH-101",
    building: "Academic Block A",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
  {
    $id: "sched-3",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    slot_id: "slot-1",
    sub_slot_id: "1C",
    day_of_week: 4,
    start_time: "10:35",
    end_time: "11:30",
    room: "LH-101",
    building: "Academic Block A",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
  // ML (Slot 2): Mon 9:30, Tue 10:35, Fri 8:30
  {
    $id: "sched-4",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-2",
    slot_id: "slot-2",
    sub_slot_id: "2A",
    day_of_week: 1,
    start_time: "09:30",
    end_time: "10:25",
    room: "LH-202",
    building: "Academic Block A",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
  {
    $id: "sched-5",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-2",
    slot_id: "slot-2",
    sub_slot_id: "2B",
    day_of_week: 2,
    start_time: "10:35",
    end_time: "11:30",
    room: "LH-202",
    building: "Academic Block A",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
  {
    $id: "sched-6",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-2",
    slot_id: "slot-2",
    sub_slot_id: "2C",
    day_of_week: 5,
    start_time: "08:30",
    end_time: "09:25",
    room: "LH-202",
    building: "Academic Block A",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
  // CN (Slot 3): Mon 10:35, Thu 8:30, Fri 9:30
  {
    $id: "sched-7",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-3",
    slot_id: "slot-3",
    sub_slot_id: "3A",
    day_of_week: 1,
    start_time: "10:35",
    end_time: "11:30",
    room: "LH-103",
    building: "Academic Block B",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
  {
    $id: "sched-8",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-3",
    slot_id: "slot-3",
    sub_slot_id: "3B",
    day_of_week: 4,
    start_time: "08:30",
    end_time: "09:25",
    room: "LH-103",
    building: "Academic Block B",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
  {
    $id: "sched-9",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-3",
    slot_id: "slot-3",
    sub_slot_id: "3C",
    day_of_week: 5,
    start_time: "09:30",
    end_time: "10:25",
    room: "LH-103",
    building: "Academic Block B",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
  // OS Lab (Lab L1): Mon 14:00-17:00
  {
    $id: "sched-10",
    $createdAt: "2024-01-15T00:00:00.000Z",
    $updatedAt: "2024-01-15T00:00:00.000Z",
    $collectionId: "class_schedules",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-4",
    slot_id: "slot-L1",
    sub_slot_id: "L1A",
    day_of_week: 1,
    start_time: "14:00",
    end_time: "17:00",
    room: "Lab-301",
    building: "Computer Centre",
    effective_from: "2024-01-15",
    effective_until: null,
    deleted_at: null,
  },
];

/**
 * Mock class occurrences (sample attendance records)
 */
export const mockClassOccurrences: ClassOccurrence[] = [
  // Some sample attendance records for the past week
  {
    $id: "occ-1",
    $createdAt: "2024-04-01T09:00:00.000Z",
    $updatedAt: "2024-04-01T09:00:00.000Z",
    $collectionId: "class_occurrences",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    schedule_id: "sched-1",
    date: "2024-04-01",
    start_time: "08:30",
    end_time: "09:25",
    status: "completed",
    cancellation_reason: null,
    rescheduled_to: null,
    attendance: "present",
    attendance_marked_at: "2024-04-01T09:30:00.000Z",
    attendance_note: null,
    is_extra_class: false,
  },
  {
    $id: "occ-2",
    $createdAt: "2024-04-02T10:00:00.000Z",
    $updatedAt: "2024-04-02T10:00:00.000Z",
    $collectionId: "class_occurrences",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    schedule_id: "sched-2",
    date: "2024-04-02",
    start_time: "09:30",
    end_time: "10:25",
    status: "completed",
    cancellation_reason: null,
    rescheduled_to: null,
    attendance: "present",
    attendance_marked_at: "2024-04-02T10:30:00.000Z",
    attendance_note: null,
    is_extra_class: false,
  },
  {
    $id: "occ-3",
    $createdAt: "2024-04-04T11:00:00.000Z",
    $updatedAt: "2024-04-04T11:00:00.000Z",
    $collectionId: "class_occurrences",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    schedule_id: "sched-3",
    date: "2024-04-04",
    start_time: "10:35",
    end_time: "11:30",
    status: "completed",
    cancellation_reason: null,
    rescheduled_to: null,
    attendance: "absent",
    attendance_marked_at: "2024-04-04T11:35:00.000Z",
    attendance_note: "Sick",
    is_extra_class: false,
  },
  // ML class cancelled
  {
    $id: "occ-4",
    $createdAt: "2024-04-01T10:00:00.000Z",
    $updatedAt: "2024-04-01T10:00:00.000Z",
    $collectionId: "class_occurrences",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-2",
    schedule_id: "sched-4",
    date: "2024-04-01",
    start_time: "09:30",
    end_time: "10:25",
    status: "cancelled",
    cancellation_reason: "Faculty on leave",
    rescheduled_to: null,
    attendance: null,
    attendance_marked_at: null,
    attendance_note: null,
    is_extra_class: false,
  },
];

/**
 * Mock exams data
 */
export const mockExams: Exam[] = [
  {
    $id: "exam-1",
    $createdAt: "2024-03-01T00:00:00.000Z",
    $updatedAt: "2024-03-01T00:00:00.000Z",
    $collectionId: "exams",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    name: "Quiz 1",
    type: "quiz",
    date: "2024-03-15",
    start_time: "10:00",
    duration_minutes: 30,
    location: "LH-101",
    marks_obtained: 18,
    marks_total: 20,
    weightage_percent: 10,
    syllabus: "Arrays, Linked Lists",
    notes: null,
    reminder_offsets_json: null,
    status: "completed",
    deleted_at: null,
  },
  {
    $id: "exam-2",
    $createdAt: "2024-03-01T00:00:00.000Z",
    $updatedAt: "2024-03-01T00:00:00.000Z",
    $collectionId: "exams",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    name: "Midterm Exam",
    type: "midterm",
    date: "2024-04-10",
    start_time: "09:00",
    duration_minutes: 120,
    location: "Exam Hall A",
    marks_obtained: null,
    marks_total: 50,
    weightage_percent: 30,
    syllabus: "All topics till Week 8",
    notes: "Bring calculator",
    reminder_offsets_json: null,
    status: "upcoming",
    deleted_at: null,
  },
  {
    $id: "exam-3",
    $createdAt: "2024-03-01T00:00:00.000Z",
    $updatedAt: "2024-03-01T00:00:00.000Z",
    $collectionId: "exams",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-2",
    name: "Assignment 1",
    type: "assignment",
    date: "2024-04-05",
    start_time: null,
    duration_minutes: null,
    location: null,
    marks_obtained: null,
    marks_total: 25,
    weightage_percent: 15,
    syllabus: "Linear Regression, Logistic Regression",
    notes: "Submit on Moodle",
    reminder_offsets_json: null,
    status: "upcoming",
    deleted_at: null,
  },
  {
    $id: "exam-4",
    $createdAt: "2024-03-01T00:00:00.000Z",
    $updatedAt: "2024-03-01T00:00:00.000Z",
    $collectionId: "exams",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-3",
    name: "Practical Lab Test",
    type: "practical",
    date: "2024-04-12",
    start_time: "14:00",
    duration_minutes: 180,
    location: "Network Lab",
    marks_obtained: null,
    marks_total: 30,
    weightage_percent: 20,
    syllabus: "TCP/IP, Socket Programming",
    notes: null,
    reminder_offsets_json: null,
    status: "upcoming",
    deleted_at: null,
  },
];

/**
 * Mock tasks data
 */
export const mockTasks: Task[] = [
  {
    $id: "task-1",
    $createdAt: "2024-04-01T00:00:00.000Z",
    $updatedAt: "2024-04-01T00:00:00.000Z",
    $collectionId: "tasks",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    semester_id: "sem-1",
    title: "Complete DSA practice problems",
    description: "Solve 10 problems from LeetCode on Trees",
    notes: null,
    deadline: "2024-04-08T23:59:00.000Z",
    reminder_at: "2024-04-08T18:00:00.000Z",
    reminder_offsets_json: null,
    is_completed: false,
    completed_at: null,
    priority: "high",
    sort_order: 0,
    deleted_at: null,
  },
  {
    $id: "task-2",
    $createdAt: "2024-04-01T00:00:00.000Z",
    $updatedAt: "2024-04-01T00:00:00.000Z",
    $collectionId: "tasks",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-2",
    semester_id: "sem-1",
    title: "Read ML Chapter 5",
    description: "Neural Networks fundamentals",
    notes: null,
    deadline: "2024-04-06T23:59:00.000Z",
    reminder_at: null,
    reminder_offsets_json: null,
    is_completed: false,
    completed_at: null,
    priority: "medium",
    sort_order: 1,
    deleted_at: null,
  },
  {
    $id: "task-3",
    $createdAt: "2024-04-01T00:00:00.000Z",
    $updatedAt: "2024-04-02T00:00:00.000Z",
    $collectionId: "tasks",
    $databaseId: "classey",
    $permissions: [],
    subject_id: null,
    semester_id: "sem-1",
    title: "Submit library books",
    description: null,
    notes: "3 books due this week",
    deadline: "2024-04-07T17:00:00.000Z",
    reminder_at: null,
    reminder_offsets_json: null,
    is_completed: false,
    completed_at: null,
    priority: "low",
    sort_order: 2,
    deleted_at: null,
  },
  {
    $id: "task-4",
    $createdAt: "2024-03-28T00:00:00.000Z",
    $updatedAt: "2024-04-01T00:00:00.000Z",
    $collectionId: "tasks",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-3",
    semester_id: "sem-1",
    title: "Wireshark packet analysis",
    description: "Capture and analyze HTTP packets",
    notes: null,
    deadline: "2024-04-03T23:59:00.000Z",
    reminder_at: null,
    reminder_offsets_json: null,
    is_completed: true,
    completed_at: "2024-04-01T15:30:00.000Z",
    priority: "high",
    sort_order: 3,
    deleted_at: null,
  },
];

/**
 * Mock events data
 */
export const mockEvents: Event[] = [
  {
    $id: "event-1",
    $createdAt: "2024-04-01T00:00:00.000Z",
    $updatedAt: "2024-04-01T00:00:00.000Z",
    $collectionId: "events",
    $databaseId: "classey",
    $permissions: [],
    semester_id: "sem-1",
    title: "Project Demo",
    description: "Present final project to faculty panel",
    location: "Seminar Hall B",
    start_datetime: "2024-04-15T10:00:00.000Z",
    end_datetime: "2024-04-15T12:00:00.000Z",
    is_all_day: false,
    recurrence: null,
    color: "#10B981",
    deleted_at: null,
  },
  {
    $id: "event-2",
    $createdAt: "2024-04-01T00:00:00.000Z",
    $updatedAt: "2024-04-01T00:00:00.000Z",
    $collectionId: "events",
    $databaseId: "classey",
    $permissions: [],
    semester_id: null,
    title: "College Fest",
    description: "Annual technical and cultural fest",
    location: "Main Campus",
    start_datetime: "2024-04-20T00:00:00.000Z",
    end_datetime: "2024-04-22T23:59:00.000Z",
    is_all_day: true,
    recurrence: null,
    color: "#F59E0B",
    deleted_at: null,
  },
];

/**
 * Mock files data
 */
export const mockFiles: ClasseyFile[] = [
  {
    $id: "file-1",
    $createdAt: "2024-03-15T10:00:00.000Z",
    $updatedAt: "2024-03-15T10:00:00.000Z",
    $collectionId: "files",
    $databaseId: "classey",
    $permissions: [],
    storage_file_id: "storage-file-1",
    file_name: "DSA_Notes_Unit1.pdf",
    file_size: 2456789,
    mime_type: "application/pdf",
    file_extension: "pdf",
    subject_id: "sub-1",
    exam_id: null,
    task_id: null,
    event_id: null,
    occurrence_id: null,
    description: "Unit 1 - Arrays and Linked Lists notes",
    is_past_paper: false,
    deleted_at: null,
  },
  {
    $id: "file-2",
    $createdAt: "2024-03-20T14:30:00.000Z",
    $updatedAt: "2024-03-20T14:30:00.000Z",
    $collectionId: "files",
    $databaseId: "classey",
    $permissions: [],
    storage_file_id: "storage-file-2",
    file_name: "DSA_PYQ_2023.pdf",
    file_size: 1845632,
    mime_type: "application/pdf",
    file_extension: "pdf",
    subject_id: "sub-1",
    exam_id: null,
    task_id: null,
    event_id: null,
    occurrence_id: null,
    description: "Previous year question paper 2023",
    is_past_paper: true,
    deleted_at: null,
  },
  {
    $id: "file-3",
    $createdAt: "2024-04-01T09:15:00.000Z",
    $updatedAt: "2024-04-01T09:15:00.000Z",
    $collectionId: "files",
    $databaseId: "classey",
    $permissions: [],
    storage_file_id: "storage-file-3",
    file_name: "assignment_stack_queue.py",
    file_size: 4523,
    mime_type: "text/x-python",
    file_extension: "py",
    subject_id: "sub-1",
    exam_id: null,
    task_id: "task-3",
    event_id: null,
    occurrence_id: null,
    description: "Stack and Queue implementation assignment",
    is_past_paper: false,
    deleted_at: null,
  },
  {
    $id: "file-4",
    $createdAt: "2024-03-25T11:00:00.000Z",
    $updatedAt: "2024-03-25T11:00:00.000Z",
    $collectionId: "files",
    $databaseId: "classey",
    $permissions: [],
    storage_file_id: "storage-file-4",
    file_name: "ML_Lecture_Slides.pptx",
    file_size: 8765432,
    mime_type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    file_extension: "pptx",
    subject_id: "sub-2",
    exam_id: null,
    task_id: null,
    event_id: null,
    occurrence_id: null,
    description: "Week 5 lecture slides - Neural Networks",
    is_past_paper: false,
    deleted_at: null,
  },
  {
    $id: "file-5",
    $createdAt: "2024-04-02T16:30:00.000Z",
    $updatedAt: "2024-04-02T16:30:00.000Z",
    $collectionId: "files",
    $databaseId: "classey",
    $permissions: [],
    storage_file_id: "storage-file-5",
    file_name: "DBMS_ER_Diagram.png",
    file_size: 256789,
    mime_type: "image/png",
    file_extension: "png",
    subject_id: "sub-3",
    exam_id: null,
    task_id: null,
    event_id: null,
    occurrence_id: null,
    description: "ER diagram for project database",
    is_past_paper: false,
    deleted_at: null,
  },
];

/**
 * Mock resource links data
 */
export const mockResourceLinks: ResourceLink[] = [
  {
    $id: "link-1",
    $createdAt: "2024-03-10T08:00:00.000Z",
    $updatedAt: "2024-03-10T08:00:00.000Z",
    $collectionId: "resource_links",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    exam_id: null,
    title: "Abdul Bari DSA Playlist",
    url: "https://www.youtube.com/playlist?list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O",
    type: "youtube",
    description: "Complete DSA course with animations",
    thumbnail_url: "https://i.ytimg.com/vi/0IAPZzGSbME/maxresdefault.jpg",
    sort_order: 0,
    deleted_at: null,
  },
  {
    $id: "link-2",
    $createdAt: "2024-03-12T10:30:00.000Z",
    $updatedAt: "2024-03-12T10:30:00.000Z",
    $collectionId: "resource_links",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    exam_id: null,
    title: "VisuAlgo - Visualizing Algorithms",
    url: "https://visualgo.net/en",
    type: "website",
    description: "Interactive algorithm visualizations",
    thumbnail_url: null,
    sort_order: 1,
    deleted_at: null,
  },
  {
    $id: "link-3",
    $createdAt: "2024-03-15T14:00:00.000Z",
    $updatedAt: "2024-03-15T14:00:00.000Z",
    $collectionId: "resource_links",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-2",
    exam_id: null,
    title: "Andrew Ng ML Course",
    url: "https://www.youtube.com/playlist?list=PLLssT5z_DsK-h9vYZkQkYNWcItqhlRJLN",
    type: "youtube",
    description: "Stanford ML course by Andrew Ng",
    thumbnail_url: "https://i.ytimg.com/vi/jGwO_UgTS7I/maxresdefault.jpg",
    sort_order: 0,
    deleted_at: null,
  },
  {
    $id: "link-4",
    $createdAt: "2024-03-18T11:15:00.000Z",
    $updatedAt: "2024-03-18T11:15:00.000Z",
    $collectionId: "resource_links",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-2",
    exam_id: null,
    title: "ML Course Notes",
    url: "https://www.notion.so/ml-course-notes-example",
    type: "notion",
    description: "Personal notes from ML lectures",
    thumbnail_url: null,
    sort_order: 1,
    deleted_at: null,
  },
  {
    $id: "link-5",
    $createdAt: "2024-03-20T09:00:00.000Z",
    $updatedAt: "2024-03-20T09:00:00.000Z",
    $collectionId: "resource_links",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-3",
    exam_id: null,
    title: "DBMS Lecture Materials",
    url: "https://drive.google.com/drive/folders/example123",
    type: "drive",
    description: "Prof shared Google Drive folder",
    thumbnail_url: null,
    sort_order: 0,
    deleted_at: null,
  },
];

/**
 * Mock notes data
 */
export const mockNotes: Note[] = [
  {
    $id: "note-1",
    $createdAt: "2024-04-01T10:30:00.000Z",
    $updatedAt: "2024-04-01T10:30:00.000Z",
    $collectionId: "notes",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    occurrence_id: "occ-1",
    content: "Important: Linked list reversal will be asked in midterm. Practice both iterative and recursive approaches.",
    is_pinned: true,
    deleted_at: null,
  },
  {
    $id: "note-2",
    $createdAt: "2024-04-02T11:00:00.000Z",
    $updatedAt: "2024-04-02T11:00:00.000Z",
    $collectionId: "notes",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-1",
    occurrence_id: null,
    content: "Remember to practice tree traversal algorithms. BFS and DFS implementations are key for interviews.",
    is_pinned: false,
    deleted_at: null,
  },
  {
    $id: "note-3",
    $createdAt: "2024-04-03T14:15:00.000Z",
    $updatedAt: "2024-04-03T14:15:00.000Z",
    $collectionId: "notes",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-2",
    occurrence_id: null,
    content: "Neural network backpropagation derivation will be in the exam. Check Andrew Ng's video for clear explanation.",
    is_pinned: true,
    deleted_at: null,
  },
  {
    $id: "note-4",
    $createdAt: "2024-04-04T09:45:00.000Z",
    $updatedAt: "2024-04-04T09:45:00.000Z",
    $collectionId: "notes",
    $databaseId: "classey",
    $permissions: [],
    subject_id: "sub-3",
    occurrence_id: null,
    content: "SQL queries practice needed. Focus on JOINs, subqueries, and GROUP BY with HAVING clause.",
    is_pinned: false,
    deleted_at: null,
  },
];
