/**
 * Base Appwrite document fields (auto-generated by Appwrite)
 */
export interface AppwriteDocument {
  $id: string;
  $createdAt: string;
  $updatedAt: string;
  $collectionId: string;
  $databaseId: string;
  $permissions: string[];
}

/**
 * Semester entity
 */
export interface Semester extends AppwriteDocument {
  name: string;
  start_date: string;
  end_date: string;
  color: string;
  icon: string | null;
  target_spi: number | null;
  spi: number | null;
  credits_earned: number | null;
  credits_total: number | null;
  is_quick_input: boolean;
  status: "upcoming" | "ongoing" | "completed";
  is_archived: boolean;
  sort_order: number;
  deleted_at: string | null;
}

/**
 * Subject entity
 */
export interface Subject extends AppwriteDocument {
  semester_id: string;
  name: string;
  short_name: string;
  code: string | null;
  start_date: string | null;
  end_date: string | null;
  color: string;
  icon: string | null;
  attendance_requirement_percent: number | null;
  credits: number;
  grade: string | null;
  grade_points: number | null;
  grade_scale_id: string | null;
  type: "theory" | "lab" | "practical" | "project" | "other";
  slot_ids: string[];
  teacher_name: string | null;
  teacher_email: string | null;
  teacher_phone: string | null;
  telegram_notify_classes: boolean;
  sort_order: number;
  deleted_at: string | null;
}

/**
 * Sub-slot timing definition
 */
export interface SubSlot {
  id: string;
  day_of_week: 1 | 2 | 3 | 4 | 5 | 6;
  start_time: string;
  end_time: string;
}

/**
 * Slot entity
 */
export interface Slot extends AppwriteDocument {
  slot_id: string;
  name: string;
  type: "regular" | "lab" | "extra";
  sub_slots: string; // JSON stringified SubSlot[]
  is_default: boolean;
  sort_order: number;
  deleted_at: string | null;
}

/**
 * Class schedule entity
 */
export interface ClassSchedule extends AppwriteDocument {
  subject_id: string;
  slot_id: string | null;
  sub_slot_id: string | null;
  day_of_week: 1 | 2 | 3 | 4 | 5 | 6;
  start_time: string;
  end_time: string;
  room: string | null;
  building: string | null;
  effective_from: string;
  effective_until: string | null;
  deleted_at: string | null;
}

/**
 * Class occurrence (individual class session)
 */
export interface ClassOccurrence extends AppwriteDocument {
  subject_id: string;
  schedule_id: string | null;
  date: string;
  start_time: string;
  end_time: string;
  status: "scheduled" | "completed" | "cancelled" | "rescheduled";
  cancellation_reason: string | null;
  rescheduled_to: string | null;
  attendance: "present" | "absent" | null;
  attendance_marked_at: string | null;
  attendance_note: string | null;
  is_extra_class: boolean;
}

/**
 * Exam entity
 */
export interface Exam extends AppwriteDocument {
  subject_id: string;
  name: string;
  type: "quiz" | "assignment" | "midterm" | "final" | "practical" | "other";
  date: string;
  start_time: string | null;
  duration_minutes: number | null;
  location: string | null;
  marks_obtained: number | null;
  marks_total: number;
  weightage_percent: number | null;
  syllabus: string | null;
  notes: string | null;
  reminder_offsets_json: string | null;
  status: "upcoming" | "completed" | "missed";
  deleted_at: string | null;
}

/**
 * Task entity
 */
export interface Task extends AppwriteDocument {
  subject_id: string | null;
  semester_id: string | null;
  title: string;
  description: string | null;
  notes: string | null;
  deadline: string | null;
  reminder_at: string | null;
  reminder_offsets_json: string | null;
  is_completed: boolean;
  completed_at: string | null;
  priority: "urgent" | "high" | "medium" | "low" | null;
  sort_order: number;
  deleted_at: string | null;
}

/**
 * Event entity
 */
export interface Event extends AppwriteDocument {
  semester_id: string | null;
  title: string;
  description: string | null;
  location: string | null;
  start_datetime: string;
  end_datetime: string;
  is_all_day: boolean;
  recurrence: "none" | "daily" | "weekly" | "monthly" | null;
  color: string | null;
  deleted_at: string | null;
}

/**
 * Grade mapping for grade scales
 */
export interface GradeMapping {
  grade: string;
  points: number;
  min_percent: number;
}

/**
 * Grade scale entity
 */
export interface GradeScale extends AppwriteDocument {
  name: string;
  is_default: boolean;
  mappings: string; // JSON stringified GradeMapping[]
}

/**
 * Settings entity
 */
export interface Settings extends AppwriteDocument {
  user_id: string;
  theme_mode: "dark" | "light";
  background_style: "dotted" | "boxes" | "dot-pattern" | "aurora" | "beams" | "animated-grid";
  background_custom_css: string | null;
  font_family: string;
  accent_color_default: string;
  timezone: string;
  first_day_of_week: 0 | 1;
  time_format: "12h" | "24h";
  date_format: "DD/MM/YYYY" | "MM/DD/YYYY" | "YYYY-MM-DD";
  spi_scale: number;
  credits_range_max: number;
  auto_absent_hours: number;
  default_attendance_requirement: number;
  push_notifications_enabled: boolean;
  push_notify_exams: boolean;
  push_notify_assignments: boolean;
  push_notify_deadlines: boolean;
  push_notify_tasks: boolean;
  telegram_notifications_enabled: boolean;
  telegram_bot_chat_id: string | null;
  telegram_notify_exams: boolean;
  telegram_notify_assignments: boolean;
  telegram_notify_deadlines: boolean;
  telegram_notify_tasks: boolean;
  telegram_notify_classes: boolean;
  pre_class_reminder_minutes: number;
  exam_default_reminder_offsets_json: string | null;
  task_default_reminder_offsets_json: string | null;
  ai_requests_today: number;
  ai_requests_reset_date: string;
  last_opened_path: string | null;
}

export interface NotificationLog extends AppwriteDocument {
  entity_type: "exam" | "task" | "class" | "deadline" | "assignment";
  entity_id: string;
  channel: "telegram" | "push";
  sent_at: string;
  message_preview: string;
  success: boolean;
  error_message: string | null;
  dedupe_key: string | null;
  retry_count: number;
  next_retry_at: string | null;
}

export interface ReminderOffset {
  value: number;
  unit: "minutes" | "hours" | "days";
}

/**
 * Helper to parse grade mappings from JSON string
 */
export function parseGradeMappings(scale: GradeScale): GradeMapping[] {
  return JSON.parse(scale.mappings) as GradeMapping[];
}

/**
 * Helper to parse sub-slots from JSON string
 */
export function parseSubSlots(slot: Slot): SubSlot[] {
  return JSON.parse(slot.sub_slots) as SubSlot[];
}

/**
 * Computed attendance stats for a subject
 */
export interface AttendanceStats {
  total: number;
  present: number;
  absent: number;
  cancelled: number;
  percentage: number;
  classesNeeded: number; // classes to attend to reach requirement
  canBunk: number; // classes that can be bunked while staying above requirement
}

/**
 * File entity (stored in Appwrite Storage)
 */
export interface ClasseyFile extends AppwriteDocument {
  storage_file_id: string;
  file_name: string;
  file_size: number; // bytes
  mime_type: string;
  file_extension: string;
  subject_id: string | null;
  exam_id: string | null;
  task_id: string | null;
  event_id: string | null;
  occurrence_id: string | null;
  description: string | null;
  is_past_paper: boolean;
  deleted_at: string | null;
}

/**
 * Resource link entity (YouTube, Notion, Drive, etc.)
 */
export interface ResourceLink extends AppwriteDocument {
  subject_id: string;
  exam_id: string | null;
  title: string;
  url: string;
  type: "youtube" | "notion" | "drive" | "github" | "website" | "other";
  description: string | null;
  thumbnail_url: string | null;
  sort_order: number;
  deleted_at: string | null;
}

/**
 * Note entity (quick notes for classes/subjects)
 */
export interface Note extends AppwriteDocument {
  subject_id: string;
  occurrence_id: string | null;
  content: string;
  is_pinned: boolean;
  deleted_at: string | null;
}

/**
 * AI conversation message
 */
export interface AiConversation extends AppwriteDocument {
  role: "user" | "assistant";
  content: string;
  timestamp: string;
  tokens_used: number | null;
  provider: "groq" | "google" | null;
}
