/**
 * Export Utilities - Export data to JSON/PDF
 * Uses jspdf and html2canvas for PDF generation
 */

import { format } from "date-fns";
import type { Semester, Subject, Exam, Task, ClassOccurrence } from "@/types/database";

export type ExportFormat = "json" | "pdf";

export interface ExportData {
  exportedAt: string;
  version: string;
  semesters: Semester[];
  subjects: Subject[];
  exams: Exam[];
  tasks: Task[];
  attendance: ClassOccurrence[];
}

/**
 * Export all data to JSON file
 */
export function exportToJSON(data: ExportData): void {
  const jsonString = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonString], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement("a");
  link.href = url;
  link.download = `classey-export-${format(new Date(), "yyyy-MM-dd")}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export semester summary to PDF
 */
export async function exportSemesterToPDF(
  semester: Semester,
  subjects: Subject[],
  exams: Exam[]
): Promise<void> {
  // Dynamic import to avoid SSR issues
  const { jsPDF } = await import("jspdf");
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;
  
  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(semester.name, pageWidth / 2, yPos, { align: "center" });
  yPos += 10;
  
  // Date range
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    `${format(new Date(semester.start_date), "MMM d, yyyy")} - ${format(new Date(semester.end_date), "MMM d, yyyy")}`,
    pageWidth / 2,
    yPos,
    { align: "center" }
  );
  yPos += 15;
  
  // SPI/Target
  if (semester.spi || semester.target_spi) {
    doc.setFontSize(12);
    if (semester.spi) {
      doc.text(`SPI: ${semester.spi.toFixed(2)}`, 20, yPos);
    }
    if (semester.target_spi) {
      doc.text(`Target: ${semester.target_spi.toFixed(2)}`, 80, yPos);
    }
    yPos += 10;
  }
  
  // Divider
  doc.setDrawColor(200);
  doc.line(20, yPos, pageWidth - 20, yPos);
  yPos += 10;
  
  // Subjects
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Subjects", 20, yPos);
  yPos += 8;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  subjects.forEach((subject) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFont("helvetica", "bold");
    doc.text(`${subject.short_name} - ${subject.name}`, 20, yPos);
    yPos += 5;
    
    doc.setFont("helvetica", "normal");
    doc.text(`Credits: ${subject.credits} | Type: ${subject.type}`, 25, yPos);
    if (subject.grade) {
      doc.text(`Grade: ${subject.grade}`, 100, yPos);
    }
    yPos += 8;
  });
  
  yPos += 5;
  
  // Exams
  if (exams.length > 0) {
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Exams", 20, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    
    exams.forEach((exam) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      
      const subject = subjects.find((s) => s.$id === exam.subject_id);
      doc.text(
        `${exam.name} (${subject?.short_name || ""}) - ${exam.date}`,
        20,
        yPos
      );
      yPos += 5;
      
      if (exam.marks_obtained !== null) {
        doc.text(
          `Score: ${exam.marks_obtained}/${exam.marks_total}`,
          25,
          yPos
        );
        yPos += 5;
      }
      yPos += 3;
    });
  }
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(
    `Generated by Classey on ${format(new Date(), "MMM d, yyyy 'at' h:mm a")}`,
    pageWidth / 2,
    285,
    { align: "center" }
  );
  
  // Save
  doc.save(`${semester.name.replace(/\s+/g, "-")}-${format(new Date(), "yyyy-MM-dd")}.pdf`);
}

/**
 * Export attendance report to PDF
 */
export async function exportAttendanceToPDF(
  subject: Subject,
  attendance: ClassOccurrence[],
  stats: { present: number; absent: number; total: number; percentage: number }
): Promise<void> {
  const { jsPDF } = await import("jspdf");
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;
  
  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(`Attendance Report: ${subject.name}`, pageWidth / 2, yPos, { align: "center" });
  yPos += 10;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`(${subject.short_name})`, pageWidth / 2, yPos, { align: "center" });
  yPos += 15;
  
  // Stats
  doc.setFontSize(12);
  doc.text(`Present: ${stats.present}`, 20, yPos);
  doc.text(`Absent: ${stats.absent}`, 70, yPos);
  doc.text(`Total: ${stats.total}`, 120, yPos);
  yPos += 7;
  
  doc.setFont("helvetica", "bold");
  doc.text(`Attendance: ${stats.percentage.toFixed(1)}%`, 20, yPos);
  doc.setFont("helvetica", "normal");
  yPos += 5;
  
  const required = subject.attendance_requirement_percent || 75;
  if (stats.percentage >= required) {
    doc.setTextColor(34, 197, 94); // green
    doc.text(`✓ Meets requirement (${required}%)`, 80, yPos);
  } else {
    doc.setTextColor(239, 68, 68); // red
    doc.text(`✗ Below requirement (${required}%)`, 80, yPos);
  }
  doc.setTextColor(0);
  yPos += 15;
  
  // Attendance list
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Attendance History", 20, yPos);
  yPos += 8;
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  
  const sortedAttendance = [...attendance].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );
  
  sortedAttendance.forEach((record) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    
    const status = record.attendance === "present" ? "✓ Present" : "✗ Absent";
    const color = record.attendance === "present" ? [34, 197, 94] : [239, 68, 68];
    
    doc.text(format(new Date(record.date), "MMM d, yyyy"), 20, yPos);
    doc.text(`${record.start_time} - ${record.end_time}`, 70, yPos);
    doc.setTextColor(color[0], color[1], color[2]);
    doc.text(status, 120, yPos);
    doc.setTextColor(0);
    yPos += 6;
  });
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(
    `Generated by Classey on ${format(new Date(), "MMM d, yyyy 'at' h:mm a")}`,
    pageWidth / 2,
    285,
    { align: "center" }
  );
  
  // Save
  doc.save(`attendance-${subject.short_name}-${format(new Date(), "yyyy-MM-dd")}.pdf`);
}

/**
 * Generate timetable image for export
 */
export async function exportTimetableToImage(
  elementId: string,
  filename: string
): Promise<void> {
  const html2canvas = (await import("html2canvas")).default;
  
  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id "${elementId}" not found`);
  }
  
  const canvas = await html2canvas(element, {
    scale: 2,
    backgroundColor: "#1a1a1a",
    logging: false,
  });
  
  const link = document.createElement("a");
  link.download = `${filename}-${format(new Date(), "yyyy-MM-dd")}.png`;
  link.href = canvas.toDataURL("image/png");
  link.click();
}
